services:
  - type: web
    name: storehub-merchant-onboarding-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://onboardingmanager.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
