services:
  - type: web
    name: storehub-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    # Add post-deploy hook to seed terms and conditions
    postDeployCommand: npm run seed:terms || echo "Terms seeding completed or already exists"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: FRONTEND_URL
        value: https://onboardingmanager-1.onrender.com
      - key: GOOGLE_CLIENT_ID
        value: YOUR_GOOGLE_CLIENT_ID_HERE
      - key: GOOGLE_CLIENT_SECRET
        value: YOUR_GOOGLE_CLIENT_SECRET_HERE
      - key: GOOGLE_CALLBACK_URL
        value: https://storehub-backend.onrender.com/api/auth/google/callback
      - key: ALLOWED_OAUTH_DOMAINS
        value: "@storehub.com,@gmail.com"
      - key: DATABASE_URL
        fromDatabase:
          name: storehub-postgres
          property: connectionString

databases:
  - name: storehub-postgres
    databaseName: storehub_onboarding
    user: storehub_user
    plan: starter
